# Dracut configs for generating initramfs.

# Ensure dracut builds a generic image, not one tied to the build host hardware.
hostonly="no"
# Force adding btrfs and key ufs drivers.
add_dracutmodules+=" btrfs "
force_drivers+=" ufs_qcom ufshcd_pltfrm "